### ISSUE TITLE
git tags

### ISSUE THREAD

**Issue by noraj** [Pennyw0rth/NetExec#10]
Ref. https://github.com/Porchetta-Industries/CrackMapExec/issues/800

If this become the official cme community fork, could you please recreate at least all previous git tags and create new git tags and github release for cme 6.0 and 6.1 please.

**Comment by noraj** [comment]
One example among many, this is required by many distribution packages.

[![Packaging status](https://repology.org/badge/vertical-allrepos/crackmapexec.svg)](https://repology.org/project/crackmapexec/versions)

**Comment by XiaoliChan** [comment]
> If this become the official cme community fork.

At present, this is impossible... ¯\\_(ツ)_/¯

**Comment by noraj** [comment]
> > If this become the official cme community fork.
> 
> At present, this is impossible... ¯\_(ツ)_/¯

https://github.com/Porchetta-Industries/CrackMapExec/discussions/801 was locked, it's pretty clear that the community will continue to work on CME on the fork and that bytebleeder wi'll abandon cme or shutdown prochetta.

> Published this repository into the package source will cause another unnecessary conflict with porchetta

But anyway I'm just asking for git tags here, each package manager of each distro will choose which upstream repository to follow. And I guess if the community push changes here while porchetta repository stay stale or is archived this is just a question of time before the change will be reflected everywhere.

**Comment by Marshall-Hallenbeck** [comment]
Since we'll have to rename, we will need to do a whole bunch of work, including pip/apt configuration, etc. I assume with the rename we'll start at version 1, but internal discussion is on-going.

**Comment by Marshall-Hallenbeck** [comment]
We have started using tags with the release of v1.0.0: https://github.com/Pennyw0rth/NetExec/releases/tag/v1.0.0
