### ISSUE TITLE
Module ms17-010 is falsely reporting "not vulnerable", despite the target being vulnerable.

### ISSUE THREAD

**Issue by SebastianApel** [Pennyw0rth/NetExec#101]
**Describe the bug**
The module ms17-010 is always reporting "not vulnerable", despite the target being vulnerable.  

This is because the module code itself is not working with python3, but the errors are being catched by the try/except/finally wrapper, more specifically the "except: return false" part.

**To Reproduce**
- Tested with HackTheBox Machine "Blue"
- Remove the try/except/finally block and look at the error messages

**Expected behavior**
The module should report vulnerable ms17-010 instances.

**Screenshots**
This screenshot was created after replacing line 437 with "raise" to propagate the error.

![image](https://github.com/Pennyw0rth/NetExec/assets/13675545/9a39d402-8bd2-468c-b9c7-f9a5a4a8c8a1)

**Additional information**
The python code in the following link is a python3 conversion from the python2 code that was used for the module. The converted python3 version is working for me:
https://gist.github.com/mdawsonuk/caac9ec724abe4e70277c6a2478629da

**Comment by Marshall-Hallenbeck** [comment]
@SebastianApel is this with the newest version from the `develop` branch or an older version?

**Comment by SebastianApel** [comment]
I have tested both versions - both are not working. The code is not converted to python3. 

The python code in the following link is a python3 conversion from the original python2 code. It is working for me:
https://gist.github.com/mdawsonuk/caac9ec724abe4e70277c6a2478629da

**Comment by Marshall-Hallenbeck** [comment]
@SebastianApel Okay thanks, we'll take a look and try to get a fix out! Appreciate the bug report.
