### ISSUE TITLE
Option `--domain` does not override internal domain

### ISSUE THREAD

**Issue by NeffIsBack** [Pennyw0rth/NetExec#102]
**Describe the bug**
Usually the option `--domain`/`-d` should override the domain retreived by impacket. This is clearly not the case here
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/f579bdc6-ab3c-4f3d-884a-49cab7a16547)

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `netexec smb -u username -p password --domain SOMETHING_INVALID`
Successful login

**Expected behavior**
This should not result in a login, rather it should fail as this furthermore suggests that specifying the domain manually does not work.

**NetExec info**
 - OS: Kali rolling
 - Version of nxc: github-upstream
 - Installed from: pipx+github

**Comment by XiaoliChan** [comment]
The `--domain` flag only working on `Domain Computers` group member, not `Domain Controllers`

**Comment by mpgn** [comment]
Do you know why using a wrong domain is working on a Domain Controllers @XiaoliChan ? (i'm curious)

**Comment by XiaoliChan** [comment]
> Do you know why using a wrong domain is working on a Domain Controllers @XiaoliChan ? (i'm curious)

I don't know why, I just test again any check the event log, when I using `non-existed.com\xiaoli` login into the DC, the event log said I was logon as `xiaoli.local/xiaoli`

**Comment by NeffIsBack** [comment]
> I don't know why, I just test again any check the event log, when I using `non-existed.com\xiaoli` login into the DC, the event log said I was logon as `xiaoli.local/xiaoli`

Did you do that from cme or from the windows UI? Or is it also possible directly on the dc?

**Comment by XiaoliChan** [comment]
> Did you do that from cme or from the windows UI? Or is it also possible directly on the dc?

I test it with impacket’s smbclient.py

**Comment by mpgn** [comment]
not an issue ^^
