### ISSUE TITLE
Kerberoasting not returning any output

### ISSUE THREAD

**Issue by rafaariza** [Pennyw0rth/NetExec#104]
**Describe the bug**
When using the `--kerberoasting` flag the tool returns an error while using `GetUserSPNs` from Impacket does not.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `nxc ldap 172.16.5.5 -u forend -p Klmcargo2 --kerberoasting kerberoasting`
Resulted in:
![image](https://github.com/Pennyw0rth/NetExec/assets/64159271/56c12c10-07a7-4f1a-860e-2f12d46d3beb)

**NetExec info**
 - OS: Parrot
 - Version of nxc: commit 470b4e88cca88d6d315de854430b88fc635dae8a dev branch
 - Installed from: cloning repo -> pipx

**Comment by Marshall-Hallenbeck** [comment]
> Can confirm this is broken

Same. Working on a fix now.

**Comment by Marshall-Hallenbeck** [comment]
@rafaariza Should be fixed in the `develop` branch :)
