### ISSUE TITLE
Tracebacks when using Win binary

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#124]
The latest .exe has nasty issue. It's impossible to use smb bruteforce because _every single_ unsuccessful attempt also brings a lot of traceback information. It's big mess. As you can see, there's no STATUS_LOGON_FAILURE line

[20:32:29] ERROR    Exception while calling proto_flow() on target 192.168.1.1: too many values to unpack (expected 2)                                                        connection.py:123
                    ╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
                    │ in login:3501                                                                                                                                           │
                    │                                                                                                                                                         │
                    │ in login_extended:3436                                                                                                                                  │
                    │                                                                                                                                                         │
                    │ in isValidAnswer:785                                                                                                                                    │
                    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    SessionError: SMB SessionError: code: 0xc000006d - STATUS_LOGON_FAILURE - The attempted logon is invalid. This is either due to a bad username or
                    authentication information.

                    During handling of the above exception, another exception occurred:

                    ╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
                    │ in login:276                                                                                                                                            │
                    │                                                                                                                                                         │
                    │ in login:3505                                                                                                                                           │
                    │                                                                                                                                                         │
                    │ in login_extended:3436                                                                                                                                  │
                    │                                                                                                                                                         │
                    │ in isValidAnswer:785                                                                                                                                    │
                    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    SessionError: SMB SessionError: code: 0xc000006d - STATUS_LOGON_FAILURE - The attempted logon is invalid. This is either due to a bad username or
                    authentication information.

                    During handling of the above exception, another exception occurred:

                    ╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
                    │ C:\Users\poop\AppData\Local\Temp\_MEI23722\nxc\protocols\smb.py:465 in plaintext_login                                                                   │
                    │                                                                                                                                                         │
                    │    462 │   │   │   self.domain = domain                                                                                                                 │
                    │    463 │   │   │                                                                                                                                        │
                    │    464 │   │   │   try:                                                                                                                                 │
                    │ ❱  465 │   │   │   │   self.conn.login(self.username, self.password, domain)                                                                            │
                    │    466 │   │   │   except UnicodeEncodeError:                                                                                                           │
                    │    467 │   │   │   │   self.logger.error(f"UnicodeEncodeError on:                                                                                       │
                    │        '{self.username}:{self.password}'. Trying again with a different encoding...")                                                                   │
                    │    468 │   │   │   │   self.create_conn_obj()                                                                                                           │
                    │                                                                                                                                                         │
                    │ in login:280                                                                                                                                            │
                    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    SessionError: SMB SessionError: code: 0xc000006d - STATUS_LOGON_FAILURE - The attempted logon is invalid. This is either due to a bad username or
                    authentication information.

                    During handling of the above exception, another exception occurred:

                    ╭─────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────╮
                    │ in __init__:121                                                                                                                                         │
                    │                                                                                                                                                         │
                    │ in proto_flow:168                                                                                                                                       │
                    │                                                                                                                                                         │
                    │ in login:465                                                                                                                                            │
                    │                                                                                                                                                         │
                    │ in try_credentials:407                                                                                                                                  │
                    │                                                                                                                                                         │
                    │ C:\Users\foo\AppData\Local\Temp\_MEI23722\nxc\protocols\smb.py:503 in plaintext_login                                                                   │
                    │                                                                                                                                                         │
                    │    500 │   │   │   │   self.create_conn_obj()                                                                                                           │
                    │    501 │   │   │   return True                                                                                                                          │
                    │    502 │   │   except SessionError as e:                                                                                                                │
                    │ ❱  503 │   │   │   error, desc = e.getErrorString()                                                                                                     │
                    │    504 │   │   │   self.logger.fail(                                                                                                                    │
                    │    505 │   │   │   │   f'{domain}\\{self.username}:{process_secret(self.password)} {error}                                                              │
                    │        {f"({desc})" if self.args.verbose else ""}',                                                                                                     │
                    │    506 │   │   │   │   color="magenta" if error in smb_error_status else "red",                                                                         │
                    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    ValueError: too many values to unpack (expected 2)

^^^ that is just unsuccessful attempt.

**Comment by NeffIsBack** [comment]
That is likely because the binaries were build around the time impacket changed the error handling. This is fixed on GitHub

@Marshall-Hallenbeck could you build new binaries and add them to the release?

**Comment by Marshall-Hallenbeck** [comment]
Building new v1.1.1 binaries now

**Comment by Marshall-Hallenbeck** [comment]
Binaries updated. @bongobongoland sorry about that, forgot to rebuild and upload when we fixed the impacket fork! Should be working now.
