### ISSUE TITLE
How to update via pipx?

### ISSUE THREAD

**Issue by TianwenOVO** [Pennyw0rth/NetExec#125]
How to update installed via pipx? When I use pipx install git+https://github.com/Pennyw0rth/NetExec to update, I will be prompted that netexec already exists.

**Comment by NeffIsBack** [comment]
Yes, updating can be done using `pipx upgrade netexec` or if you want to force pulling the latest commits use `pipx reinstall netexec`. 
`pipx upgrade netexec` will only pull down new changes when a new version bump happened.

**Comment by TianwenOVO** [comment]
> 是的，可以使用 来完成更新`pipx upgrade netexec`，或者如果您想强制拉取最新提交，请使用`pipx reinstall netexec`。 `pipx upgrade netexec`仅当发生新版本冲突时才会下拉新的更改。

Thank you!!!
