### ISSUE TITLE
Win Bin - Firefox not working anymore?

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#134]
seeing this constantly whilst running --dpapi

![image](https://github.com/Pennyw0rth/NetExec/assets/129246896/887ea390-a267-4c29-a3e7-bbbbd73bd5a4)

**Comment by NeffIsBack** [comment]
Can you try #135? This should be fixed in there

**Comment by bongobongoland** [comment]
Hey Alex.
I think - I'm not 100% sure though, need more test :) - but looks like it did the trick!
