### ISSUE TITLE
RDP module issues

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#14]
@XiaoliChan 

I know it's actually not the module problem but an issue with that particular host. However, maybe you have some ideas how to deal with this. Please, have a look. Cheers.

<img width="1328" alt="rdpissue" src="https://github.com/Pennyw0rth/NetExec/assets/129246896/a065876f-2b55-4699-9501-c921e031bf23">

**Comment by XiaoliChan** [comment]
This is probably something like NAS？

**Comment by XiaoliChan** [comment]
> Oh, oops. You think that's not windows host? :))

Yes, I have met that case before.

**Comment by bongobongoland** [comment]
Thanks @XiaoliChan

**Comment by bongobongoland** [comment]
Closing.

**Comment by bongobongoland** [comment]
<img width="1115" alt="RDPOOps" src="https://github.com/Pennyw0rth/NetExec/assets/129246896/449dc0d9-f618-41e7-b35e-d7870dce4078">

@XiaoliChan 
The first method (WMI) didn't work as you can see. It wasn't successful. Even though it says "success".
SMB did the trick though.

**Comment by XiaoliChan** [comment]
> SMB did the trick though.

What is the target OS?

**Comment by bongobongoland** [comment]
You can see the error message on the screenshot. The WMI Session Error. There's nothing else.

**Comment by XiaoliChan** [comment]
> You can see the error message on the screenshot. The WMI Session Error. There's nothing else.

I need "--debug" for full traceback log

**Comment by bongobongoland** [comment]
<img width="1554" alt="WMIRDP" src="https://github.com/Pennyw0rth/NetExec/assets/129246896/914ba6a3-be7a-4677-9342-a576d66f9600">

**Comment by XiaoliChan** [comment]
Weird, I never met that before.

Can you try with disable? `-o ACTION=disable`

**Comment by bongobongoland** [comment]
same error.

INFO     Disabled RDP services and setting up firewall.

 ERROR    WMI Session Error: code: 0x80041016 - WBEM_E_INVALID_OPERATION

**Comment by XiaoliChan** [comment]
> ERROR WMI Session Error: code: 0x80041016 - WBEM_E_INVALID_OPERATION

weird

**Comment by XiaoliChan** [comment]
The `invalid` always means the wmi class exists but is given a wrong argument using the class

**Comment by bongobongoland** [comment]
with OLD the error is slightly different
WMI Session Error: code: 0x80041010 - WBEM_E_INVALID_CLASS

**Comment by XiaoliChan** [comment]
> with OLD the error is slightly different WMI Session Error: code: 0x80041010 - WBEM_E_INVALID_CLASS

I see, What happens if you change the code in `rdp.py` line `273`

from

```
iWbemClassObject.SetAllowTSConnections(1,1)

to

iWbemClassObject.SetAllowTSConnections(1)
```

**Comment by bongobongoland** [comment]
ERROR    Function called with 1 parameters instead of 2!  
:)

**Comment by XiaoliChan** [comment]
> ERROR Function called with 1 parameters instead of 2! :)

Dammit, this is really weird XD
