### ISSUE TITLE
pipx installation fails "Package cannot be a url"

### ISSUE THREAD

**Issue by k4nfr3** [Pennyw0rth/NetExec#147]
**Describe the bug**
Installation fails with pipx

**To Reproduce**
 pipx install git+https://github.com/Pennyw0rth/NetExec
I get error "Package cannot be a url"

**Additional context**
pipx version 0.12.3.1
OS : Ubuntu 20.04.6 LTS

**Comment by NeffIsBack** [comment]
If I recall correctly pipx 0.12 is heavily outdated. Please try to update it and try again

**Comment by k4nfr3** [comment]
thank you
