### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by fu3fi** [Pennyw0rth/NetExec#170]
To deploy via poetry on Windows, you need to install rust and also change pyreadline to pyreadline3. Please update dependencies and instructions!

**Comment by NeffIsBack** [comment]
> I encountered a [similar problem](https://stackoverflow.com/questions/69515086/error-attributeerror-collections-has-no-attribute-callable-using-beautifu). I use windows 10. I don't use pipx, but collect it with poetry. Perhaps this is the issue. pyreadline -> pyreadline3 helped me

Did that occured while using nxc or nxcdb? I can verify now nxcdb is crashing on my side as well, removing pyreadline solves that. Is there a problem with nxc as well?

**Comment by NeffIsBack** [comment]
But it did happen on nxc itself? Can you provide me the command that produced that error?

**Comment by fu3fi** [comment]
Now I repeated the experiment by installing via pipx and indeed, with nxcdb I get the error AttributeError: module 'collections' has no attribute 'Callable'. nxc seems to be working fine.

**Comment by NeffIsBack** [comment]
Ok great 👍

**Comment by fu3fi** [comment]
Perhaps poetry saved something in the cache, so it was not possible to view the bug through it.
