### ISSUE TITLE
NXC Audit Mode Bug

### ISSUE THREAD

**Issue by pgormington-r7** [Pennyw0rth/NetExec#178]
**Audit Mode Repeat**
Currently `audit_mode` set in `~/.nxc/nxc.conf` is repeated 8 times due to `nxc/config.py`

**To Reproduce**
Steps to reproduce the behavior i.e.:
Set `audit_mode` in `~/.nxc/nxc.conf` to a value.
Command: `netexec smb -u username -p password`
Resulted in:
![image](https://github.com/Pennyw0rth/NetExec/assets/111919054/9365923d-0bd0-4228-937f-878e88920a1d)

```
➜  NetExec git:(main) ✗ NetExec smb 10.8.8.200 -u Administrator -p 'password`
SMB         10.8.8.200      445    PC1              [*] Windows 10.0 Build 19041 x64 (name:PC1) (domain:AD.lab) (signing:False) (SMBv1:False)
SMB         10.8.8.200      445    PC1              [+] AD.lab\Administrator:[Redacted][Redacted][Redacted][Redacted][Redacted][Redacted][Redacted][Redacted] (Admin!)

```
**Expected behavior**
Redacted text is displayed once.

**Screenshots**
Current behavior:
![image](https://github.com/Pennyw0rth/NetExec/assets/111919054/251e1248-699d-4e87-bc30-18ba418e0d9c)
Updated `nxc/config.py`:
![image](https://github.com/Pennyw0rth/NetExec/assets/111919054/d75cda24-98c3-4638-911c-85ab5004fb33)
Updated behavior:
![image](https://github.com/Pennyw0rth/NetExec/assets/111919054/b2128bc0-bbd0-4d0a-8fa9-ef8020b57c77)

**NetExec info**
 - OS: Kali
 - Version of nxc: 1.0.0 - nxc4u
 - Installed from: Github via Poetry and via Pipx

**Resolution**
Update line 47 in `nxc/config.py` to `return text if not audit_mode else hidden + colored(f"{audit_mode}, host_info_colors[1], attrs=["bold"]` and add termcolor import.

**Comment by mpgn** [comment]
It's not a bug, it is expected to put one char like "*" or whatever, not a full string ^^ 

But i agreee it can be a string and the code need to be updated

**Comment by pgormington-r7** [comment]
Ah, I was going off this post from twitter showing a full word being used. https://twitter.com/_bin_Ash/status/1533661116106252288

Makes sense to me either way but thought it was worth a callout

**Comment by NeffIsBack** [comment]
Good idea tho, i added that option in #179
