### ISSUE TITLE
Delay for password spraying

### ISSUE THREAD

**Issue by brettgus** [Pennyw0rth/NetExec#181]
Netexec is great for password spraying, but it'd be amazing if there was a way to specify a delay between each authentication attempt.

There are some [workarounds](https://github.com/3ndG4me/spray_wrapper), but it'd really nice if this was a native feature in nxc.

**Comment by NeffIsBack** [comment]
I think it's not that easy because of the "threading" of each target connection. Would throttling per target be enough? Or is there a use case where you would want to throttle, while still attacking multiple hosts?

**Comment by brettgus** [comment]
That makes sense.  When I'm password spraying I'm always doing it against the domain controller, or an individual host.  For spraying, yeah, throttling per target would be adequate.

**Comment by mpgn** [comment]
You can use `--jitter` it's kind of what you want but not exactly

**Comment by BeetleChunks** [comment]
+1

**Comment by brettgus** [comment]
@mpgn --jitter doesn't appear to help for this situation.  When spraying against a single server (which is the use case I was talking about), it appears the initial connection is delayed, but each password attempt has no delay between them.

**Comment by NeffIsBack** [comment]
As many people have requested this feature in the past, I have changed the jitter function from what I believe was a connection throttle back when CME was single threaded, to an authentication throttle.

You can install it from the `neff-jitter` branch. Try it out and leave some feedback, if that's what you are looking for.
Installation: `pipx install git+https://github.com/Pennyw0rth/NetExec@neff-jitter`

Syntax: 

- `nxc --jitter 3 smb...` will do a random 0-3 seconds delay
- `nxc --jitter 2-5 smb...` will do a random 2-5 seconds delay
- `nxc --jitter 5-5 smb...` will do an exact delay of 5 seconds

Keep in mind, this only works on a per-target basis!

**Comment by brettgus** [comment]
Thank you!  Tried it out and that's working as I was hoping.
