### ISSUE TITLE
-o flag being ignored on SMB slinky module

### ISSUE THREAD

**Issue by RunRenegade** [Pennyw0rth/NetExec#192]
**Describe the bug**
When attempting to run the Slinky module for SMB the first `-o` option is being ignored. nxc then states that the delcared option is 'required`, despite being present.

Hope I haven't just made a mistake, have gone through wiki and tried different variations. 

**To Reproduce**
Run any below code.
Tried " " as through it might be a standard input problem.
When I swapped which option was first (NAME or SERVER) it was also the first option that was ignored.

`netexec smb targets.txt -id 3 -d MARVEL.local -M slinky -o NAME=Annual -o SERVER=192.168.71.129`

`netexec smb targets.txt -id 3 -d MARVEL.local -M slinky -o SERVER="192.168.71.129" -o NAME="Annual pay rise"`

`netexec smb targets.txt -u adiministrator -p P@$$W0RD -d MARVEL.local -o NAME="Annual pay rise" -o SERVER=192.168.71.129 -M slinky`

**Expected behavior**
I would expect slinky to accept the `-o NAME=Annual`.

**Screenshots**
Attached an example of commands.

**Additional context**
None.
![slinky](https://github.com/Pennyw0rth/NetExec/assets/6189906/a390b47e-df6a-43ac-a176-aa4b8da3ce74)

**Comment by NeffIsBack** [comment]
Use `-o` only once: `-o NAME=xxxx SERVER=yyyyyy` :)

**Comment by RunRenegade** [comment]
I feel like a fool!

Thanks for the quick response!

**Comment by NeffIsBack** [comment]
Happens :) no problem

**Comment by NeffIsBack** [comment]
Btw if you need help there is always our discord server
