### ISSUE TITLE
NetExec doesn't properly support multi-threading in SSH brute forcing

### ISSUE THREAD

**Issue by Reelix** [Pennyw0rth/NetExec#194]
**Describe the bug**
When attempting to brute force a remote SSH service with multiple threads, NetExec runs at the identical speed of a single thread.

**To Reproduce**
Run the following 3 commands - Note the execution speed
`nxc --verbose ssh 10.10.235.57 -u myusername -p ~/wordlists/10k-most-common.txt --port 1234`
`nxc -t 4 --verbose ssh 10.10.235.57 -u myusername -p ~/wordlists/10k-most-common.txt --port 1234`
`nxc -t 16 --verbose ssh 10.10.235.57 -u myusername -p ~/wordlists/10k-most-common.txt --port 1234`

**Expected behavior**
On a remote service running SSH on port 1234 and no fail2ban service (Or any other filtering), the increased thread count should result in faster attempts (Ideally with the increased verbosity showing the thread on each attempt).

**Actual behavior**
Each instance runs the exact same speed.

**NetExec info**
 - OS: Ubuntu 23.10
 - Version of nxc: 1.1.0 (Codename: nxc4u)
 - Installed from: `pipx install git+https://github.com/Pennyw0rth/NetExec`

**Comment by Marshall-Hallenbeck** [comment]
This is because each _target_ is in its own thread, so if you run it against a single target, the amount of threads you specify is useless.

You can view how the threads are created here: https://github.com/Pennyw0rth/NetExec/blob/31b2a1f458f0fbb194c6dc4d7f4a46469ea8bc5c/nxc/netexec.py#L41

**Comment by Marshall-Hallenbeck** [comment]
Closing issue as answered. Please let us know if there are any other questions.
