### ISSUE TITLE
Feature request; Kerberos user enumeration (kerbrute userenum)

### ISSUE THREAD

**Issue by LucasParsy** [Pennyw0rth/NetExec#195]
Hello,

Does NetExec contain a feature doing as `kerbrute userenum` ?
[Kerbrute](https://github.com/ropnop/kerbrute?tab=readme-ov-file#user-enumeration) sends TGT requests with no pre-authentication, and depending on the server answer, can detect if a user exists or not.

If this feature dos not exist on NetExec and you deem it pertinent, **I would be happy contributing**
As I didn't contribute to nxc yet, if you could guide me on the best way I could integrate to the codebase that would be perfect.
(Would it be a core feature or a module? Do you have already existing Kerberos utils methods that I could use?)

**Comment by mpgn** [comment]
try this :)

`nxc smb <hostname> -u userlist -p '' -k`

**Comment by LucasParsy** [comment]
thanks a lot! 
maybe I can add this to the [nxc documentation - Enumerate Domain Users?]( https://www.netexec.wiki/smb-protocol/enumeration/enumerate-domain-users) ?

**Comment by exploide** [comment]
> try this :)
> 
> `nxc smb <hostname> -u userlist -p '' -k`

One difference I observed: In contrast to what kerbrute is doing, this will increase the `badPwdCount`.
Kind of obvious since it tries preauth with an empty password but I thought it is worth noting.
