### ISSUE TITLE
[NetExec Kali Packaging] New Release Tag

### ISSUE THREAD

**Issue by Arszilla** [Pennyw0rth/NetExec#199]
Hey there,

I am currently packaging `netexec` for Kali as per https://bugs.kali.org/view.php?id=8533 - With the changes to `pyproject.toml` etc. it'd be great if a new tag could be created to reflect the latest (stable) state of `netexec`, to make packaging and maintenance easier.

**Comment by NeffIsBack** [comment]
How fast do you need it? We could try to release a new version the next weeks.
Otherwise, how complicated is it to use the "old" netexec version and update it as soon as the release is done?

**Comment by Marshall-Hallenbeck** [comment]
I was just thinking we need to cut a new release soon anyway. I think once @XiaoliChan's work is merged in we can probably release v1.2 if that's okay with the other maintainers.

**Comment by Arszilla** [comment]
I'll package it as `20240312-0kali1` (provisionally) then. When the update arrives, I'll make the switch to the latest tag.

One of the reasons I brought this issue up was because I was packing based on the `1.1.0` release, which contained several dependencies like `resource` and `pyreadline`, which are a pain (because of how recursive it got - especially with `resource`). Not to mention, `pyreadline` was a Windows-only library, which was a big problem - until I checked the repo ~30 minutes ago and realized you guys removed that already...

Luckily, I had already packaged `dploot` earlier last week. So, in theory, I already have a working `netexec` package for Kali, but I wanted to release it with proper tag/version info if possible.

**Comment by NeffIsBack** [comment]
Sounds good👍🏼 thanks for the packaging!

Yeah pyreadline already caused some headaches...

**Comment by Arszilla** [comment]
Initial release/package is now available: https://gitlab.com/Arszilla/netexec

An update might be expected - as per https://bugs.kali.org/view.php?id=8533#c19010

**Comment by Marshall-Hallenbeck** [comment]
NetExec has been released on Kali!
