### ISSUE TITLE
users user returns all users instead of specified user

### ISSUE THREAD

**Issue by sdcampbell** [Pennyw0rth/NetExec#203]
**Describe the bug**
When using the `--users <user>` options, the domain controller returns all domain users instead of the specified user.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `netexec smb <hostname> -u username -p password --users <username>`
Resulted in: The output returned all users instead of the specified user.

**Expected behavior**
The help output states:

```
--users [USER]        enumerate domain users, if a user is specified than only its information is queried.
```

When running netexec with `--users <username>` I would expect to see output about only that user.

**Screenshots**
No screenshot due to protection of customer data.

**NetExec info**
 - OS: Kali, latest version
 - Version of nxc: Latest version just installed from Github using:
 
```
sudo apt install pipx git
pipx ensurepath
pipx install git+https://github.com/Pennyw0rth/NetExec
```

**Comment by Marshall-Hallenbeck** [comment]
Can confirm, and also the ldap version doesn't accept just a user.

Thanks for the report, I'll get on top of fixing this.

**Comment by Marshall-Hallenbeck** [comment]
@sdcampbell Fix for this is in the branch `issues/203`, with a few more nice things, including printing the last password set date. Please let me know if this is sufficient.
