### ISSUE TITLE
Fortra/impacket v. Pennyw0rth/impacket Conflict Resolution

### ISSUE THREAD

**Issue by Arszilla** [Pennyw0rth/NetExec#205]
As discussed in Discord, I am opening this issue to track progress and solve this issue.

Since Fortra’s `impacket` Debian package (`python3-impacket`) is maintained by Debian's Debian Python Team and is a reverse dependency for various penetration testing tools, including the libraries used by `netexec`, the creation of another `impacket` package (of [Pennyw0rth/impacket](https://github.com/Pennyw0rth/impacket)) on Kali’s side (with a different package name (`python3-impacket-nxc`), and potentially with `Replaces` or `Conflicts` headers) is not a possibility. Thus, thwarting `netexec`'s packaging on Kali side.

As a result; a potential solution is that [Pennyw0rth/impacket](https://github.com/Pennyw0rth/impacket) may need a name change, resulting in a different namespace for the library, other than `impacket`. This means both the [Pennyw0rth/impacket](https://github.com/Pennyw0rth/impacket) repo and [Pennyw0rth/netexec](https://github.com/Pennyw0rth/netexec) will require an update to reflect the change in dependency name.

**Comment by NeffIsBack** [comment]
As we swapped back to fortra/impacket with #234 i will close this issue
