### ISSUE TITLE
badpwdcount feature from CME missing 

### ISSUE THREAD

**Issue by allendemoura** [Pennyw0rth/NetExec#219]
it seems the badpwdcount output has been removed when enumerating users with `--users`

CME output:
![image](https://github.com/Pennyw0rth/NetExec/assets/90939597/c9b8e5ef-1d19-449a-9c78-709b6d1652f2)

NXC output:
![image](https://github.com/Pennyw0rth/NetExec/assets/90939597/1f44a95d-1235-4e0f-ac86-66c91bfbd98b)

is this a bug, or was the feature removed/moved elsewhere? couldn't find any mention of badpwdcount in the nxc wiki.

**Comment by Marshall-Hallenbeck** [comment]
I've got #214 and #215 open to change the SMB & LDAP `--users`, since when we changed how it worked it removed some stuff. I'll see if adding the bad password count as a default along with the last pw set still looks good.

**Comment by Marshall-Hallenbeck** [comment]
@allendemoura please check the `issue/203` branch and let me know if that is good

**Comment by allendemoura** [comment]
looks good! here's the output of master and `issue/203` next to one another for your development pleasure:
![image](https://github.com/Pennyw0rth/NetExec/assets/90939597/5e0c9b92-08d3-4d91-b7f5-fd926421f913)

and here's a check to see if the pw count is updating accurately (yes!):
![image](https://github.com/Pennyw0rth/NetExec/assets/90939597/221bef32-669b-4916-9daa-b29fc8ec9030)

blown away by your responsiveness! love this tool and look forward to contributing to it when i have more time.

on another note, i saw that you have several branches working on LDAP. i wanst able to get anything off the DC in this lab despite LDAP ports being open on it. i assumed it was the design of the lab as LDAP wasnt necessary to solve it, but worth asking, is LDAP working in the current master release? i didnt see anything suggesting otherwise in the issues section but thought i'd ask to be sure.

thanks again 🤘

**Comment by allendemoura** [comment]
oops, just noticed that the new branch does not prepend the domain (medtech.com) to domain users. its pictured above but i missed it on first glance.

**Comment by Marshall-Hallenbeck** [comment]
@allendemoura glad to know it's working, thanks for pointing this out!

LDAP is definitely working, my branch is about getting the `--users` functionality on par with the SMB version, and a few of the other ones are related to reducing dependencies and improving output, but the connection should work.

Yeah as for printing the domain, we actually removed it because the domain is printed in the lines above, and removing it from the username output saves a lot of space if there's longer usernames.

**Comment by NeffIsBack** [comment]
> oops, just noticed that the new branch does not prepend the domain (medtech.com) to domain users. its pictured above but i missed it on first glance.

yes we removed it as it is always the local host that is returned, so it isn't even correct to prepend the domain (for example for the local Administrator on a non DC)

**Comment by allendemoura** [comment]
understood, good point. less clutter sounds good to me!

**Comment by allendemoura** [comment]
is this something that'll be merged to master immediately or will it wait for a new release?

**Comment by Marshall-Hallenbeck** [comment]
> is this something that'll be merged to master immediately or will it wait for a new release?

Already merged to `main` :)

**Comment by Marshall-Hallenbeck** [comment]
> is this something that'll be merged to master immediately or will it wait for a new release?

the SMB one is already merge to `main` :)

**Comment by allendemoura** [comment]
awesome. whats your (PyPI) release schedule looking like? should i `--force` an install thru pipx to get the latest `main`? scared of nuking my configs or messing something up as i'm in the middle of a lab (`pipx upgrade` just tells me i already have 1.1.0)

**Comment by Marshall-Hallenbeck** [comment]
> awesome. whats your (PyPI) release schedule looking like? should i `--force` an install thru pipx to get the latest `main`? scared of nuking my configs or messing something up as i'm in the middle of a lab (`pipx upgrade` just tells me i already have 1.1.0)

We don't release to PyPi due to some packaging issues.

Yeah, just force reinstall - it shouldn't nuke your config. You can backup your ~/.nxc/ folder if you are worried about that, though.

**Comment by allendemoura** [comment]
ah ok thank you. i'll be using nxc a lot, so i'm curious, where do the pipx releases come from, just the gh repo releases? should i be using `--force` to update in general, or do you plan on continuing releases here on the repo?

**Comment by NeffIsBack** [comment]
Config changes are generally not overwritten, just added if they are missing. Sometimes there are database changes if you would wanna use nxcdb, but then we will make sure that you don't lose data (worst case you would have to checkout an old version and use the nxcdb from there).

**Comment by allendemoura** [comment]
awesome. thanks for the clarification, and thanks for your time!
