### ISSUE TITLE
WCC Module Creating Arbitrary Empty Log Files

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [Pennyw0rth/NetExec#256]
**Describe the bug**
The WCC module has some custom logging code that creates a ton of empty log files

**To Reproduce**
Run the WCC module
Command: `netexec smb -u username -p password -M wcc`

**Expected behavior**
Log files should have actual data in them, or they shouldn't be created

**Screenshots**
![image](https://github.com/Pennyw0rth/NetExec/assets/1518719/39cfc79f-b6a9-4168-8f05-65ac07249389)

**NetExec info**
 - OS: Kali
 - Version of nxc: 1.1.0 - nxc4u - b123a4dc
 - Installed from: `main` branch, via poetry

**Additional context**
I think we should implement a way for any module/etc to create specific logs to their needs, i.e. if a module wants to log something for users to look up later, like files created/hashes/etc, we should have an easy logging method outside our context.log/nxc_logger

**Comment by Marshall-Hallenbeck** [comment]
Ohhh since we import the modules every nxc run it's creating the logger file EACH TIME NXC IS RAN. Definitely going to be at least fixing that shortly.

**Comment by NeffIsBack** [comment]
Oh god. But atleast nxc only imports all modules when `-L` or a specific module is specified.
