### ISSUE TITLE
Bug: SSH protocol prints "could not decrypt private key" when failing to login with password

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [Pennyw0rth/NetExec#268]
**Describe the bug**
Recently some changes went into fixing using an encrypted SSH key, but unfortunately now when a non-SSH key login fails (just a password), it prints the "could not decrypt private key" error

**To Reproduce**
Attempt to login with `nxc ssh` with a bad password

**Expected behavior**
It should say login failed, but not say that there was a failure with decrypting a key

**Screenshots**
![image](https://github.com/Pennyw0rth/NetExec/assets/1518719/20827e38-c128-432d-975b-b521304d5214)

**NetExec info**
 - OS: Kali
 - Version of nxc: 1.1.0 - nxc4u - 7d44b11c
 - Installed from: Poetry

**Comment by NeffIsBack** [comment]
We need the dafuq label back lol
