### ISSUE TITLE
--continue-on-success disables --shares

### ISSUE THREAD

**Issue by SecJoe** [Pennyw0rth/NetExec#275]
**Describe the bug**
nxc smb has the option --shares which is very nice to show share permissions. But also i want to find all possible shares, so i also use the option --continue-on-success. But if i use this option, --shares will be ignored. Is this a bug?

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: ` nxc smb ./private-ips.txt -u username -p password --continue-on-success --shares`

Resulted in:
```
[...]
SMB         172.16.222.6    445    xxx             [+] test.com\username:password 
SMB         172.16.222.5    445    yyy             [+] test.com\username:password
SMB         172.16.222.15   445    zzz             [+] test.com\username:password
[...]
```

**Expected behavior**
I want to see the share permission: 
```
[...]
SMB         172.16.222.6    445    xxx            [+] test.com\username:password 
SMB         172.16.222.6   445    zzz             [*] Enumerated shares
SMB         172.16.222.6   445    zzz             Share           Permissions     Remark
SMB         172.16.222.6   445    zzz             -----           -----------     ------
SMB         172.16.222.6  445    zzz             ADMIN$                          Remote Admin
SMB         172.16.222.6   445    zzz             C$                              Default share
SMB         172.16.222.6   445    zzz             IPC$            READ            Remote IPC
[...]
```

**NetExec info**
 - OS: Kali
 - Version of nxc: v1.1.0

**Comment by NeffIsBack** [comment]
Currently nxc is not designed to open up connections for multiple users per host. `--continue-on-success` is only for password cracking and will stop the execution after the login attempt.

Also see #266
