### ISSUE TITLE
Where to create

### ISSUE THREAD

**Issue by JackeyLov5** [Pennyw0rth/NetExec#287]
Hello 👋 this is my first time using nxc, I'm coming from cme!
<img width="377" alt="image" src="https://github.com/Pennyw0rth/NetExec/assets/130417202/fae3bc22-3867-44d4-b2cf-6b1fa56bbf3a">
May I ask where the files created here are located? How do I go about deleting them when I don't need nxc or when I need to move to a VM altogether?

One more question what is the abbreviation for the tool, nxc? If so I think it should have a more aggressive full name and a catchy abbreviation. Helps me to introduce it to people Thanks!

**Comment by NeffIsBack** [comment]
Hi and welcome :) 
the folder with all the files is placed in `~/.nxc`, just as cme. So if you want to remove all the files (uninstall it) and remove that folder.

Regarding the name, the full name is NetExec with nxc being the abbreviation for easy of use.

**Comment by NeffIsBack** [comment]
We also have a wiki where you can read all the stuff: https://www.netexec.wiki/

**Comment by JackeyLov5** [comment]
&gt; We also have a wiki where you can read all the stuff: https://www.netexec.wiki/

How should it work in PrinterBug?

**Comment by NeffIsBack** [comment]
What do you mean?
PrinterBug is currently not documented on the wiki, but you can take a look at the description (`nxc smb -L`) or read the module options

**Comment by JackeyLov5** [comment]
> 你是什​​么意思？ PrinterBug 目前没有在 wiki 上记录，但你可以查看描述 ( `nxc smb -L`) 或阅读模块选项

1. For example, does rubeus have a monitoring function in the PrinterBug vulnerability? 
2. Or is there no forwarding function similar to impact ntlmrelay? 
3.What is the positioning of netexec?

**Comment by NeffIsBack** [comment]
I think there is something lost in translation, I don't fully understand the questions.

If you ask what NetExec does, it triggers the coercion and reports if the target is vulnerable. You can also set the listener IP address to get the coerced authentication.
