### ISSUE TITLE
Output issue when ssh

### ISSUE THREAD

**Issue by madabu977** [Pennyw0rth/NetExec#312]
Hi!!
I have netexec installed with pipx on kali arm64 VMware fusion (Professional Version 13.5.2) running latest version kali-rolling

Static hostname: kalix
Icon name: computer-vm
Chassis: vm 
Machine ID: xxx
Boot ID: xxx
Virtualization: vmware
Operating System: Kali GNU/Linux Rolling             
Kernel: Linux 6.6.15-arm64
Architecture: arm64
Hardware Vendor: VMware, Inc.
Hardware Model: VMware20,1
Firmware Version: VMW201.00V.21805430.BA64.2305221830

`Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2024.1
Codename:       kali-rolling`

when running 
`nxc ssh 192.168.159.230 -u users.txt -p pass.txt`

I get 
`ERROR    Error reading SSH protocol banner`

![Screenshot-3](https://github.com/Pennyw0rth/NetExec/assets/135357701/584a6e76-2849-4cfc-a8dc-4c5fd1c9dc70)

![Screenshot -1](https://github.com/Pennyw0rth/NetExec/assets/135357701/cd1c0736-228c-4a57-8a60-548d91182727)

![Screenshot-2](https://github.com/Pennyw0rth/NetExec/assets/135357701/f5b2a3a6-125d-4a2a-a7f5-144ee1130a72)

any help?
thanks in advance ;)

**Comment by NeffIsBack** [comment]
What is the first error message? Some kind of EOFError? Do you know what the target is?

Please also provide the output of `nxc --version`, but I fear this is a paramiko issue.

**Comment by madabu977** [comment]
`nxc --version`
1.1.0 - nxc4u - e3baadb

target? vulnerable machine inside vpn. its there any difference if target different ?

firt error you mean first image? 
all three images are screenshots from terminal when using nxc... same scan but at different timing.

if it is a paramiko issue... any advice?

**Comment by NeffIsBack** [comment]
Possibly related: https://github.com/paramiko/paramiko/issues/1752

**Comment by NeffIsBack** [comment]
I also pushed a possible fix to `neff-fix-ssh` which you could try. If you are using pipx do: `pipx install --force git+https://github.com/Pennyw0rth/NetExec@neff-fix-ssh`

**Comment by madabu977** [comment]
after `pipx install --force git+https://github.com/Pennyw0rth/NetExec@neff-fix-ssh` same error.

sorry but not sure how to use `nxc --debug ` which parameters should I add ? syntax? 

hopefully this EOFError screenshot helps...

![Screenshot-5](https://github.com/Pennyw0rth/NetExec/assets/135357701/d09b7f31-8170-43b3-b9f6-b9cc98e4ad31)

running same command `nxc ssh <target ip> -u user -p wordlist.txt` with `cme` give me no errors...

**Comment by NeffIsBack** [comment]
The debug flag musst be added directly after nxc so `nxc --debug <ip> -u <user>...`. Yeah cme used to have a different way to connect with ssh.

**Comment by madabu977** [comment]
well `debug` output its huge/confusing (at least for me)... here some screenshots 
![Screenshot-dbug1](https://github.com/Pennyw0rth/NetExec/assets/135357701/527b4ed9-e24c-4e2c-81e6-4e87d899ae07)
![Screenshotdebug4](https://github.com/Pennyw0rth/NetExec/assets/135357701/dee2ac07-8356-4ce4-bfee-43b859ad7d34)
![Screenshotdbug2](https://github.com/Pennyw0rth/NetExec/assets/135357701/5d2b4e6f-50d6-476f-8623-6d706391df94)
![Screenshot dbug3](https://github.com/Pennyw0rth/NetExec/assets/135357701/803ee656-f72c-4236-b3c8-07d628584f98)

all 3 screenshots are consecutive (or almost) kinda concatenated...  
helpful?

**Comment by NeffIsBack** [comment]
Yes indeed very helpful, thanks! Can you retry? Just execute `pipx reinstall netexec` and it will get the latest commit i pushed.

**Comment by madabu977** [comment]
after `pipx reinstall netexec` still not working.
increasing `--ssh-timeout 200` doesn't fix it.
here some screenshots...

![Screenshot 2024-05-19 at 6 57 17 PM](https://github.com/Pennyw0rth/NetExec/assets/135357701/b7b65f13-7eee-4b4c-9d8c-d3f78e90ecb9)
![Screenshot 2024-05-19 at 6 57 50 PM](https://github.com/Pennyw0rth/NetExec/assets/135357701/1cc364e9-9bc3-4f04-bcda-cb9f4680eff6)
![Screenshot 2024-05-19 at 6 58 47 PM](https://github.com/Pennyw0rth/NetExec/assets/135357701/148e8e0b-3a15-415b-a2b9-794d30e4f949)

**Comment by NeffIsBack** [comment]
Hmm yes thanks, i am now able to reproduce it on my system as well. It is definitely an issue in paramiko, maybe we should just mute the error and continue

**Comment by NeffIsBack** [comment]
I will open up a PR which will handle the error. I guess this is some kind of race condition inside paramiko

**Comment by madabu977** [comment]
well whatever fix you guys find just let me know... 
you guys rocks btw... ;)

**Comment by NeffIsBack** [comment]
Just pushed the error handling, with `pipx reinstall netexec` you should have it as well (in the future when this is merged you should switch your installation back to the main branch though).

Thanks! :) ✌️

**Comment by madabu977** [comment]
after `pipx reinstall netexec` error output kinda suppressed/fix.
now...
![Screenshot 2024-05-19 at 7 16 50 PM](https://github.com/Pennyw0rth/NetExec/assets/135357701/d0f80998-b5f9-4441-b970-634f38065b56)

**Comment by NeffIsBack** [comment]
Ugh that's still quite a lot of errors. Maybe retrying would be a better solution?

**Comment by madabu977** [comment]
retrying? you mean reinstalling nxc?

**Comment by NeffIsBack** [comment]
Ah sorry I meant retrying the authentication if paramiko fails to retrieve the ssh banner and therefore skipping the credential pair

**Comment by madabu977** [comment]
that might work. Please just let me know if any news/fix... and/or when should I switch to main branch.
Any solution will be cool. I don't mind to use `cme` but just love `nxc`, and knowing you guys are really behind it well it just make it even better :smile:

**Comment by NeffIsBack** [comment]
Hmm not sure if it is a good solution to implement a janky fix. I would be more happy if they fix it inside paramiko so we don't have to work around that issue. 
But you can already switch back to main as the PR has been merged. If i push a new update i'll let you know :)

**Comment by Marshall-Hallenbeck** [comment]
Yeah cme suppressed TONS of errors and would silently break all the time.
