### ISSUE TITLE
Cookie stealer

### ISSUE THREAD

**Issue by domwhewell-sage** [Pennyw0rth/NetExec#337]
**Please Describe The Problem To Be Solved**
It doesn't look like there is a module to extract cookies from the different browser sqlite databases. All users would be considered in scope except the windows built in users

**(Optional): Suggest A Solution**
There could be a module for each browser i.e. `firefox_cookies.py`, `chrome_cookies.py` etc. or a single `cookie_stealer.py` module that auto detects what browser each user has installed and extracts their cookies.
These modules should print them in JSON format so they can be pasted into a browser extension.

I've looked at Firefox and chrome so far and their browser profiles are stored in the users app data folder so the module would crawl this folder for each user looking for the `cookies.db` that is stored there and use `sqlite3` to open the database and `win32crypt` to extract the encryption key.

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)

If these modules sound good I can have a go at creating a PR

**Comment by Marshall-Hallenbeck** [comment]
This is possible via the `--dpapi cookies` command :)

**Comment by domwhewell-sage** [comment]
Ah thank you!
