### ISSUE TITLE
Dependency resolution issue

### ISSUE THREAD

**Issue by dazzgt** [Pennyw0rth/NetExec#383]
**Describe the bug**
Update of pyOpenSSL in impacket form version 21 to 24 resulted in dependency conflict with dptool, that using older cryptography.

**To Reproduce**
Just try to install NetExec through pipx
Command: `pipx install git+https://github.com/Pennyw0rth/NetExec`
Resulted in:
pipx output
```
   /home/dazzgt/.local/state/pipx/log/cmd_2024-07-25_18.08.30_pip_errors.log

pip seemed to fail to build package:
    dploot<3.0.0,>=2.7.1

Some possibly relevant errors from pip install:
    ERROR: Cannot install impacket and netexec because these package versions have conflicting dependencies.

```
log file of pipx
```
The conflict is caused by:
    dploot 2.7.1 depends on cryptography<41.0.0 and >=40.0.1
    pyopenssl 24.0.0 depends on cryptography<43 and >=41.0.5

```

**Comment by NeffIsBack** [comment]
Thanks for the report!
@zblurx updated dploot in #384 to resolve the conflict, can you retest?

**Comment by dazzgt** [comment]
Retested. All works fine. Include smb --dpapi. Thanks!
