### ISSUE TITLE
Continue with command execution on successful authentication

### ISSUE THREAD

**Issue by cmprmsd** [Pennyw0rth/NetExec#420]
**Describe the bug**
When I use `--no-bruteforce --continue-on-success` and `-x` in combination the command is currently not executed.

**To Reproduce**
Command: `netexec ssh server -u users.txt -p password.txt --no-bruteforce --continue-on-success -x ls`
Resulted in:
```
netexec ssh server -u users.txt -p password.txt --no-bruteforce --continue-on-success -x ls
SSH         10.10.10.10  445    server             [*] OpenSSH XYZ
SSH         10.10.10.10  445    server             [+] domain\username:password
SSH         10.10.10.10  445    server             [+] domain\username2:password2
Traceback (most recent call last):
...
```

**Expected behavior**
The command ls should be executed in each user's context.

**NetExec info**
 - Version of nxc: v1.2.0
 - Installed from: blackarch repo

**Comment by NeffIsBack** [comment]
Hi, thanks for the report, but this is intended behavior.
See #275 and #266

**Comment by cmprmsd** [comment]
I see. Just wrapped the script with some hacky bash to achieve my goals as a workaround for now. 
Thanks anyways!
