### ISSUE TITLE
NXCDB not storing data, missing creds and other options

### ISSUE THREAD

**Issue by skmagiik** [Pennyw0rth/NetExec#424]
**Describe the bug**
With a fresh Kali VM and installation of netexec via either apt install netexec or building manually I cannot get working nxcdb
When I run the netexec I get valid results which should be stored in the database. For example successful login credentials or petitpotam vulnerable detections.

**To Reproduce**
Once I run the database and send help there is no option for creds, hosts, etc

**Expected behavior**
The results should appear in the nxcdb. I tried to observe where in the source this should occur, but the help menu seems to be abstracted away somewhere I couldn't see where the failure occurs.

**NetExec info**
 - OS:  Kali
 - Version of nxc: 1.2.0
 - Installed from: apt or github

**Comment by Adamkadaban** [comment]
You have to change the protocol first with `proto smb`. Then `creds` will work

**Comment by skmagiik** [comment]
That worked, it would be helpful if help indicated that in any way during usage.

**Comment by Adamkadaban** [comment]
btw @skmagiik 

you forgot to censor one of the paths for your exam. and the hashes behind your transparent terminal
not sure if that matters for pnpt, but :shrug:
