### ISSUE TITLE
 SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by sec13b** [Pennyw0rth/NetExec#439]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SyntaxWarning: invalid escape sequence '\ '
  """,
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SyntaxWarning: invalid escape sequence '\{'
  command = self.__shell + "echo " + data + f" ^> \\\\127.0.0.1\\{self.__share_name}\\{self.__output} 2^>^&1 > %TEMP%\{self.__batchFile} & %COMSPEC% /Q /c %TEMP%\{self.__batchFile} & %COMSPEC% /Q /c del %TEMP%\{self.__batchFile}"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

How i solve this ?

thank you

**Comment by NeffIsBack** [comment]
Hi, how did you get this warning? Which command and how did you install NetExec?

**Comment by NeffIsBack** [comment]
Okay, thanks for reporting! I will fix them soon.
Though, these are just syntax warnings and not errors, so they don't affect the programs behaviour.

**Comment by NeffIsBack** [comment]
Please provide:
- `poetry run netexec --version`
- The full file&line number of the Syntax warnings

**Comment by NeffIsBack** [comment]
Please provide the file and line number that is included in the warning. Otherwise i won't be able to fix it
