### ISSUE TITLE
mac arm cannot be used

### ISSUE THREAD

**Issue by Asn0w** [Pennyw0rth/NetExec#477]
My computer is mac m1
I tried to install it using pipx, but the installation was not successful. The python version is 3.9.
Directly download the compiled file, use the smb function and there is no return
![image](https://github.com/user-attachments/assets/7697b5d9-6ceb-4044-9982-91d09b5f678a)
![image](https://github.com/user-attachments/assets/667fa9da-1c0b-47c1-a5ec-ffbe81242b42)

**Comment by NeffIsBack** [comment]
If you don't get an output from the smb protocol you most likely have no connection to the host. Are you sure you can reach it? You could try to use `--debug` and see what is happening
