### ISSUE TITLE
Constant lxml issue on Mac m1/m2

### ISSUE THREAD

**Issue by rach1tarora** [Pennyw0rth/NetExec#489]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Building wheel for impacket (pyproject.toml) ... done
  Created wheel for impacket: filename=impacket-0.13.0.dev0+20241024.90011.835e175-py3-none-any.whl size=1593720 sha256=a35975df7d259f6c7d8eefcc3b601bedb19a7f135a76ae6a0d38c7f88079e0ee
  Stored in directory: /private/var/folders/hr/gmdrvmf95b36nlnr9clmcx100000gn/T/pip-ephem-wheel-cache-kg_sfrkc/wheels/91/bb/cd/3677c58ae36d295fbd93608e451428d2f4d282bed527905141
  Building wheel for pynfsclient (pyproject.toml) ... done
  Created wheel for pynfsclient: filename=pyNfsClient-0.1.5-py2.py3-none-any.whl size=37361 sha256=3b04670bf2d8135567a80b24f4f9e9e1e49b9011b873afdba1cb54eec22fd50e
  Stored in directory: /private/var/folders/hr/gmdrvmf95b36nlnr9clmcx100000gn/T/pip-ephem-wheel-cache-kg_sfrkc/wheels/72/cf/ec/b7f7546493df28bbb98681a9158e568809dc723bd641fb6de8
Successfully built netexec impacket pynfsclient
Failed to build lxml
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml)

I have tried every workaround, this just doesn't seem to work

**Comment by NeffIsBack** [comment]
How did you try to install it?

**Comment by NeffIsBack** [comment]
And what is your python version?

**Comment by NeffIsBack** [comment]
Looks like this is an issue with python 3.13. lxml fails to build on my machine with that py version as well, we will fix it soon

**Comment by NeffIsBack** [comment]
Until then you could install nxc with a different python version

**Comment by NeffIsBack** [comment]
If you do need a workaround i can give you something hacky, but better you use python 3.12 as this is tested and supported

**Comment by KeyStrOke95** [comment]
Ensure that Python 3.12 is installed: 
```
brew install python@3.12
```
Then, identify it's location:
```
$ which python3.12
/usr/local/bin/python3.12
```
Finally, use the following command to specify the Python version for pipx.
```
$ pipx install git+https://github.com/Pennyw0rth/NetExec --python /usr/local/bin/python3.12
```
This ensures the package is installed without any issues.

**Comment by rach1tarora** [comment]
Thank you! I'm glad that this turned out to be a bug and not me being lazy. I will install this with the workaround, thank you for your help
