### ISSUE TITLE
unable to run nxc/netexec

### ISSUE THREAD

**Issue by weesuan** [Pennyw0rth/NetExec#494]
Hi, am unable to run netexec/nxc somehow after installation.
Can anyone pls help?

┌──(kali㉿kali)-[~]
└─$ sudo pipx install git+https://github.com/Pennyw0rth/NetExec
⚠  Note: netexec was already on your PATH at /usr/bin/netexec
⚠  Note: nxc was already on your PATH at /usr/bin/nxc
⚠  Note: nxcdb was already on your PATH at /usr/bin/nxcdb
  installed package netexec 1.3.0+05ad3c6, installed using Python 3.12.7
  These apps are now globally available
    - NetExec
    - netexec
    - nxc
    - nxcdb
⚠  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx
    ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (e.g. ~/.bashrc).
done! ✨ 🌟 ✨
                                                                                                                                                             
┌──(kali㉿kali)-[~]
└─$ echo $PATH 
/home/kali/.local/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/kali/.dotnet/tools:/home/kali/.local/bin
                                                                                                                                                             
┌──(kali㉿kali)-[~]
└─$ nxc    
Traceback (most recent call last):
  File "/home/kali/.local/bin/nxc", line 5, in <module>
    from nxc.netexec import main
ModuleNotFoundError: No module named 'nxc'

**Comment by NeffIsBack** [comment]
Hi.
Never do the installation with root! This will lead to several different issues. Just install nxc with your normal user:
```sh
sudo pipx uninstall netexec
pipx install git+https://github.com/Pennyw0rth/NetExec
```
