### ISSUE TITLE
Add Kerberos usage

### ISSUE THREAD

**Issue by w2xim3** [Pennyw0rth/NetExec#501]
It would be very nice to include kerberos 

Something like:

nxc kerberos spnscan --domain <DOMAIN> --user <USERNAME> --password <PASSWORD> --dc-ip <DC_IP>

**Comment by NeffIsBack** [comment]
What do you mean by "include kerberos"? We got kerberos authentication

**Comment by w2xim3** [comment]
I believe I didn't express my request clearly. Anyway, it would be interesting to integrate Impacket's functionalities into a Kerberos feature.

**Comment by NeffIsBack** [comment]
What exactly would you like to have as a kerberos feature from impacket? Do you mean GetUserSPNs for NetExec?

**Comment by w2xim3** [comment]
nxc kerberos spn -u 'user' -p 'pass' --dc-ip <DC_IP>
nxc kerberos tgt --request -u 'User' -p 'Password' --dc-ip <DC_IP>

**Comment by Marshall-Hallenbeck** [comment]
> Something like
> 
> nxc kerberos spn -u 'user' -p 'pass' --dc-ip <DC_IP> nxc kerberos tgt --request -u 'User' -p 'Password' --dc-ip <DC_IP>

There is no kerberos protocol in nxc, but we allow kerberos authentication for several protocols.

Are you asking to add in a feature to request & save a ticket via kerberos, then use that to authenticate?

**Comment by NeffIsBack** [comment]
Not sure if we would like to support that. If there is a need you could just use getTGT.py from the impacket library. But i guess it would be easy to implement it

**Comment by lodos2005** [comment]
https://www.netexec.wiki/getting-started/using-kerberos there is a kerberos authentication

but if you are only looking for a method to perform Kerberoasting or ASREPRoast attacks, you can use the following commands:

nxc ldap 192.168.0.104 -u harry -p pass --asreproast output.txt
nxc ldap 192.168.0.104 -u harry -p pass --kerberoasting output.txt

you can check the links,
https://www.netexec.wiki/ldap-protocol/asreproast
https://www.netexec.wiki/ldap-protocol/kerberoasting
