### ISSUE TITLE
Passwords cannot be exported for higher versions of Veeam and Veeam using pgsql database

### ISSUE THREAD

**Issue by ZredamanJ** [Pennyw0rth/NetExec#517]
Passwords cannot be exported for higher versions of Veeam
![image](https://github.com/user-attachments/assets/60e1cb2e-1062-4a46-a0c5-75313bf5e17d)

For lower versions of veeam, you can export passwords
![image](https://github.com/user-attachments/assets/32a06196-22cc-46c4-8ad4-43ac33452819)

At the same time, I would like to ask, what is the principle of remotely exporting the veeam database password? Can you teach me?

**Comment by Marshall-Hallenbeck** [comment]
@NeffIsBack Looks like the v12 dump isn't working for some reason.

@ZredamanJ can you provide a debug log (via `--debug`) of running it against v12? We have a specific codeblock for v11 vs v12 but something isn't working properly I guess.

>what is the principle of remotely exporting the veeam database password? Can you teach me?

I'm not sure I understand this question, are you asking why people would want to dump a database password?

**Comment by ZredamanJ** [comment]
@Marshall-Hallenbeck 
debug log
![image](https://github.com/user-attachments/assets/8f266c23-b116-41a2-b101-5a6ddd5fc8e6)

[01:55:07] DEBUG    NXC VERSION: 0.0.0 - NeedForSpeed - 6d4fdfd                                                                                                                                          cli.py:26
           DEBUG    PYTHON VERSION: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]                                                                                 netexec.py:80
           DEBUG    RUNNING ON: Windows Release: 10                                                                                                                                                  netexec.py:81
           DEBUG    Passed args: Namespace(version=False, threads=256, timeout=None, jitter=None, verbose=False, debug=True, no_progress=False, log=None, force_ipv6=False, dns_server=None,         netexec.py:82
                    dns_tcp=False, dns_timeout=3, protocol='smb', target=['10.10.10.135'], username=['administrator'], password=['admin!@#45'], cred_id=[], ignore_pw_decoding=False,
                    no_bruteforce=False, continue_on_success=False, gfail_limit=None, ufail_limit=None, fail_limit=None, kerberos=False, use_kcache=False, aesKey=None, kdcHost=None,
                    server='https', server_host='0.0.0.0', server_port=None, connectback_host=None, module=['veeam'], module_options=[], list_modules=False, show_module_options=False, hash=[],
                    delegate=None, no_s4u2proxy=False, domain=None, local_auth=True, port=445, share='C$', smb_server_port=445, gen_relay_list=None, smb_timeout=2, laps=None, sam=False, lsa=False,
                    ntds=None, dpapi=None, sccm=None, mkfile=None, pvk=None, enabled=False, userntds=None, shares=False, interfaces=False, no_write_check=False, filter_shares=None, sessions=False,
                    disks=False, loggedon_users_filter=None, loggedon_users=False, users=None, groups=None, computers=None, local_groups=None, pass_pol=False, rid_brute=None, wmi=None,
                    wmi_namespace='root\\cimv2', spider=None, spider_folder='.', content=False, exclude_dirs='', depth=None, only_files=False, pattern=None, regex=None, put_file=None,
                    get_file=None, append_host=False, exec_method='wmiexec', dcom_timeout=5, get_output_tries=100, codec='utf-8', no_output=False, execute=None, ps_execute=None, obfs=False,
                    amsi_bypass=None, clear_obfscripts=False, force_ps32=False, no_encode=False)
           DEBUG    Protocol: smb                                                                                                                                                                   netexec.py:136
           DEBUG    Protocol Path: C:\Users\zr\AppData\Local\Temp\_MEI638602\nxc\protocols\smb.py                                                                                                   netexec.py:139
           DEBUG    Protocol DB Path: C:\Users\zr\AppData\Local\Temp\_MEI638602\nxc\protocols\smb\database.py                                                                                       netexec.py:141
[01:55:08] DEBUG    Protocol Object: <class 'protocol.smb'>, type: <class 'type'>                                                                                                                   netexec.py:144
           DEBUG    Protocol DB Object: <class 'protocol.database'>                                                                                                                                 netexec.py:146
           DEBUG    DB Path: C:\Users\zr/.nxc\workspaces\default\smb.db                                                                                                                             netexec.py:149
           DEBUG    symmetric using "pyCryptodomex" for "DES"                                                                                                                                       __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "TDES"                                                                                                                                      __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "AES"                                                                                                                                       __init__.py:55
           DEBUG    symmetric using "pyCryptodomex" for "RC4"                                                                                                                                       __init__.py:55
           DEBUG    Modules to be Loaded for sanity check: ['veeam'], <class 'list'>                                                                                                                netexec.py:178
           DEBUG    Loading module for sanity check veeam at path C:\Users\zr\AppData\Local\Temp\_MEI638602\nxc\modules\veeam.py                                                                    netexec.py:185
           DEBUG    Supported protocols: ['smb']                                                                                                                                                moduleloader.py:71
           DEBUG    Protocol: smb                                                                                                                                                               moduleloader.py:72
           DEBUG    Using proactor: IocpProactor                                                                                                                                            proactor_events.py:633
           DEBUG    Creating ThreadPoolExecutor                                                                                                                                                      netexec.py:44
           DEBUG    Creating thread for <class 'protocol.smb'>                                                                                                                                       netexec.py:47
           INFO     Socket info: host=10.10.10.135, hostname=10.10.10.135, kerberos=False, ipv6=False, link-local ipv6=False                                                                     connection.py:163
           DEBUG    Kicking off proto_flow                                                                                                                                                       connection.py:225
           DEBUG    Creating SMBv1 connection to 10.10.10.135                                                                                                                                           smb.py:526
           INFO     Error creating SMBv1 connection to 10.10.10.135: Error occurs while reading from remote(10054)                                                                                      smb.py:542
           DEBUG    Creating SMBv3 connection to 10.10.10.135                                                                                                                                           smb.py:547
           DEBUG    Created connection object                                                                                                                                                    connection.py:230
           DEBUG    Server OS: Windows 10 / Server 2019 Build 18362 10.0 build 18362                                                                                                                    smb.py:265
           DEBUG    Update Hosts: [{'id': 4, 'ip': '10.10.10.135', 'hostname': 'DESKTOP-TPTNF54', 'domain': 'DESKTOP-TPTNF54', 'os': 'Windows 10 / Server 2019 Build 18362', 'dc': None, 'smbv1':  database.py:256
                    False, 'signing': False, 'spooler': None, 'zerologon': None, 'petitpotam': None}]
           DEBUG    add_host() - Host IDs Updated: [4]                                                                                                                                             database.py:266
           DEBUG    Error logging off system: Error occurs while reading from remote(10054)                                                                                                             smb.py:296
           INFO     Resolved domain: DESKTOP-TPTNF54 with dns, kdcHost: 10.10.10.135                                                                                                                    smb.py:304
           DEBUG    Creating SMBv3 connection to 10.10.10.135                                                                                                                                           smb.py:547
[01:55:09] INFO     SMB         10.10.10.135    445    DESKTOP-TPTNF54  Windows 10 / Server 2019 Build 18362 x64 (name:DESKTOP-TPTNF54) (domain:DESKTOP-TPTNF54) (signing:False) (SMBv1:False)          smb.py:313
                    SMB         10.10.10.135    445    DESKTOP-TPTNF54  Windows 10 / Server 2019 Build 18362 x64 (name:DESKTOP-TPTNF54) (domain:DESKTOP-TPTNF54) (signing:False) (SMBv1:False)
[01:55:09] DEBUG    Trying to authenticate using plaintext with domain                                                                                                                           connection.py:494
           DEBUG    Logged in with password to SMB with DESKTOP-TPTNF54/administrator                                                                                                                   smb.py:414
           DEBUG    self.is_guest=False                                                                                                                                                                 smb.py:416
           DEBUG    Checking if user is admin on 10.10.10.135                                                                                                                                           smb.py:591
           DEBUG    User is admin on 10.10.10.135!                                                                                                                                                      smb.py:606
           DEBUG    Adding credential: DESKTOP-TPTNF54/administrator:admin!@#45                                                                                                                         smb.py:420
           DEBUG    Adding credentials: [{'id': 9, 'domain': 'DESKTOP-TPTNF54', 'username': 'administrator', 'password': 'admin!@#45', 'credtype': 'plaintext', 'pillaged_from_hostid': None}]     database.py:323
           DEBUG    smb hosts() - results: [(4, '10.10.10.135', 'DESKTOP-TPTNF54', 'DESKTOP-TPTNF54', 'Windows 10 / Server 2019 Build 18362', None, False, False, None, None, None)]               database.py:475
[01:55:09] INFO     SMB         10.10.10.135    445    DESKTOP-TPTNF54  DESKTOP-TPTNF54\administrator:admin!@#45 (Pwn3d!)                                                                               smb.py:427
                    SMB         10.10.10.135    445    DESKTOP-TPTNF54  DESKTOP-TPTNF54\administrator:admin!@#45 (Pwn3d!)
           DEBUG    Adding admin user: DESKTOP-TPTNF54/administrator:admin!@#45@10.10.10.135                                                                                                            smb.py:432
           DEBUG    smb hosts() - results: [(4, '10.10.10.135', 'DESKTOP-TPTNF54', 'DESKTOP-TPTNF54', 'Windows 10 / Server 2019 Build 18362', None, False, False, None, None, None)]               database.py:475
           INFO     Loading modules for target: 10.10.10.135                                                                                                                                     connection.py:578
           DEBUG    Supported protocols: ['smb']                                                                                                                                                moduleloader.py:71
           DEBUG    Protocol: smb                                                                                                                                                               moduleloader.py:72
           DEBUG    Calling modules                                                                                                                                                              connection.py:235
           DEBUG    Loading module veeam - <NXCModule.NXCModule object at 0x0000025E6796F590>                                                                                                    connection.py:270
           DEBUG    Loading context for module veeam - <NXCModule.NXCModule object at 0x0000025E6796F590>                                                                                        connection.py:280
           DEBUG    Module veeam has on_admin_login method                                                                                                                                       connection.py:294
[01:55:09] INFO     VEEAM       10.10.10.135    445    DESKTOP-TPTNF54  Looking for Veeam installation...                                                                                              veeam.py:31
                    VEEAM       10.10.10.135    445    DESKTOP-TPTNF54  Looking for Veeam installation...
[01:55:11] INFO     VEEAM       10.10.10.135    445    DESKTOP-TPTNF54  Veeam v12 installation found!                                                                                                  veeam.py:57
                    VEEAM       10.10.10.135    445    DESKTOP-TPTNF54  Veeam v12 installation found!
[01:55:11] DEBUG    No Veeam v11 installation found                                                                                                                                                    veeam.py:94
[01:55:12] DEBUG    Closing connection to: 10.10.10.135

**Comment by ZredamanJ** [comment]
> I'm not sure I understand this question, are you asking why people would want to dump a database password?

I would like to know how to remotely dump a veeam database password

**Comment by NeffIsBack** [comment]
There was a formatting bug which was fixed recently. @ZredamanJ make sure you have the latest commits, that should fix it. Looking at the debug log I would assume you installed NetExec with apt?

**Comment by NeffIsBack** [comment]
> > I'm not sure I understand this question, are you asking why people would want to dump a database password?
> 
> 
> 
> I would like to know how to remotely dump a veeam database password

NetExec uses a PowerShell script to dump the passwords. Take a look at nxc/data/veeam. It is basically just connecting with the veeam sql database and queries the passwords

**Comment by NeffIsBack** [comment]
I see you are running probably running the windows binary from the last release. Since then the bug with the output has been fixed, although you can still see all passwords in the highlight message.
If you want the newest binary i recommend compiling it yourself with the guide from the wiki.
