### ISSUE TITLE
(Win Binary) Issue with -x/-X

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#59]
Simple -x commands work fine, however, slightly more complex commands fail. This is a Windows version issue.

For example, -x 'net group "Big Boys Group" Wannabe /add' is not going to work, it won't go thru:
`nxc.exe: error: unrecognized arguments `

-x 'net group Big Boys Group Wannabe /add' will go thru but will return 
`The group name could not be found.`

I've tried running nxc.exe in both PS and cmd.
Btw, this issue was present in cme's binary for windows.

**Comment by Dfte** [comment]
Hey dude! You need to escape your "\" otherwise it will break when building the command to run.
Can you try this:  -x 'net group \"Big Boys Group\" Wannabe /add' pls ?

**Comment by bongobongoland** [comment]
> For example, -x 'net group "Big Boys Group" Wannabe /add' is not going to work, it won't go thru: `nxc.exe: error: unrecognized arguments `

**Comment by Marshall-Hallenbeck** [comment]
This is really weird. If you log the debug output with `--debug` you can see what the command is being ran, and it _should_ run (and it runs if you run it directly in a shell on the host), but something funky is happening with the translation...

**Comment by Marshall-Hallenbeck** [comment]
@bongobongoland okay I figured it out, I think. It's not a bug, but simply Windows being stupid. Here's an example command that worked for me:
`.\nxc.exe smb ip -u 'user' -p 'pass' -x 'net group \"group name\" user2 /add'`

Note the single quotes on the outside and _ESCAPED_ double quotes on the inside.

**Comment by bongobongoland** [comment]
Yep. That's the trick. Cheers! This must be in our wiki :)

**Comment by Marshall-Hallenbeck** [comment]
Good idea - the whole Windows binary thing is pretty new (the last one was years ago), so we should definitely add this 👍
