### ISSUE TITLE
(Win Binary) Ctr + Z/C/X doesn't work

### ISSUE THREAD

**Issue by bongobongoland** [Pennyw0rth/NetExec#61]
it's an old issue with the binary for windows, I think it's time to get it fixed!

**Comment by Marshall-Hallenbeck** [comment]
@bongobongoland Can we get a better explanation?

**Comment by bongobongoland** [comment]
There's no way to stop the process. The only option is to close the terminal window.

**Comment by Dfte** [comment]
Guess we'll have to handle signals differently ?

**Comment by NeffIsBack** [comment]
I also experienced this issue multiple times on linux as well. Most often when running commands against many targets. Or atleast i had to spam ctrl+C for stopping the process.

**Comment by Marshall-Hallenbeck** [comment]
I tried with the windows binary and yeah, it doesn't like ctrl-c. Not in the same way Linux doesn't though. Definitely some sort of issue related to Windows.

**Comment by bongobongoland** [comment]
In Kali (qterminal) only Ctr+Z works fine. Sort of. If you do it a couple of times, you will see how the text cursor magically disappears. Then you'll have to do a reset of your terminal. This could be qterminal's issue (it's a bad terminal in general...)

**Comment by bongobongoland** [comment]
Any solutions to this annoying problem?

**Comment by NeffIsBack** [comment]
I looked at the problem a while ago for linux because it doesn't really work there as well and the idea i had was adding SIG. I didn't have the time yet to test that, but if anyone has feel free

**Comment by bongobongoland** [comment]
In linux you just have to spam the terminal and it works. But in Windows nothing works really.

**Comment by NeffIsBack** [comment]
I invested some time into fixing this, but apparently it is to kill the tasks scheduled by the ThreadPoolExecutor. According to [this post](https://stackoverflow.com/a/29237343/17395725) this is due to the nature of python.
As this is not fixable at the moment i am closing the issue
