### ISSUE TITLE
Feature Dark Mode Addition

### ISSUE THREAD

**Issue by Parth4git** [Pennyw0rth/NetExec#92]
Feature request

The repository looks complete with the addition of the dark mode button in navbar

Proposal
Addition of the dark mode button

Kindly assign me this issue. @NeffIsBack

**Comment by Marshall-Hallenbeck** [comment]
@Parth4git what do you mean? GitHub dark mode in your browser is based on your personal settings.

**Comment by NeffIsBack** [comment]
Nut really sure either, but here you go with the assignment :D

**Comment by Parth4git** [comment]
I want to add dark mode button in https://www.netexec.wiki/ near the search button @Marshall-Hallenbeck @NeffIsBack

**Comment by Marshall-Hallenbeck** [comment]
@mpgn Not sure if we need to enable something here? https://changelog.gitbook.com/may-2023/30-may-a-light-dark-mode-toggle-and-new-customization-options

**Comment by mpgn** [comment]
done :)
